"use client";
import {useCallback,useEffect,useState} from "react";
import {KeyRound,Save,ShieldCheck,UserPlus,X} from "lucide-react";
import {Button} from "@/components/ui/button";
const ROLES:[string,string][]=[["ADMIN","Administrator"],["MANAGER","Manager"],["STORE_MANAGER","Store Manager"],["ACCOUNTS","Accounts"],["PURCHASE","Purchase"],["WORKSHOP","Workshop"],["SERVICE_ADVISOR","Service Advisor"],["TECHNICIAN","Technician"],["VIEWER","Viewer"]];
type U={id:string;name:string;username:string;email:string;role:string;isActive:boolean;permissions:string[];usesCustomPermissions:boolean};
const GROUPS:[string,string[]][]=[
 ["Job Cards",["workshop.view","workshop.create","workshop.edit","workshop.status","workshop.parts","workshop.approve","workshop.print"]],
 ["Expenses",["expenses.view","expenses.create","expenses.edit","expenses.delete","expenses.export","expenses.dashboard"]],
 ["Inventory",["inventory.view","inventory.manage"]],["Purchase",["purchase.view","purchase.manage","purchase.approve"]],
 ["Accounts",["accounts.view","accounts.manage"]],["Sales",["sales.view","sales.manage"]],["Salary / Employees",["salary.view","salary.manage"]],
 ["Other",["dashboard.view","masters.manage","reports.view","settings.manage","users.manage"]],
];
const LABEL:Record<string,string>={"workshop.view":"View Job Cards","workshop.create":"Create Job Card","workshop.edit":"Edit Job Card","workshop.status":"Change Job Status","workshop.parts":"Issue / Return Parts","workshop.approve":"Approve Job Card","workshop.print":"Print / PDF / Share","expenses.view":"View Expenses","expenses.create":"Create Expense","expenses.edit":"Edit Expense","expenses.delete":"Delete Expense","expenses.export":"Export Expenses","expenses.dashboard":"Expense Dashboard","inventory.view":"View Inventory","inventory.manage":"Manage Inventory","purchase.view":"View Purchase","purchase.manage":"Manage Purchase","purchase.approve":"Approve Purchase","accounts.view":"View Accounts","accounts.manage":"Manage Accounts","sales.view":"View Sales","sales.manage":"Manage Sales","salary.view":"View Salary / Employees","salary.manage":"Manage Salary / Employees","dashboard.view":"Dashboard","masters.manage":"Masters","reports.view":"Reports","settings.manage":"Settings","users.manage":"Users & Access Control"};
export function UserManager(){const[users,setUsers]=useState<U[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[adding,setAdding]=useState(false),[permUser,setPermUser]=useState<U|null>(null);
 const load=useCallback(async()=>{setLoading(true);try{const r=await fetch('/api/users');const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load users');setUsers(d.users)}catch(e:any){setError(e.message)}finally{setLoading(false)}},[]);useEffect(()=>{load()},[load]);
 async function patch(id:string,b:any){const r=await fetch(`/api/users/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});const d=await r.json();if(!r.ok){setError(d.error||'Update failed');return false}setError(null);await load();return true}
 async function resetPassword(id:string,u:string){const pw=prompt(`New password for ${u}:`);if(pw)await patch(id,{password:pw})}
 async function remove(id:string,u:string){if(!confirm(`Deactivate ${u}?`))return;const r=await fetch(`/api/users/${id}`,{method:'DELETE'});const d=await r.json();if(!r.ok)setError(d.error||'Failed');else load()}
 return <div className="space-y-4"><div className="flex items-center justify-between"><div><p className="text-sm text-ink-muted">{users.length} users</p><p className="text-xs text-ink-muted">Role defaults can be overridden per user. Changes take effect immediately.</p></div><Button onClick={()=>setAdding(true)}><UserPlus className="h-4 w-4"/>Add user</Button></div>{error&&<p className="rounded-lg bg-red-50 px-4 py-2 text-sm text-red-600">{error}</p>}
 <div className="overflow-hidden rounded-2xl border bg-white dark:border-white/10 dark:bg-[rgb(var(--surface))]"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-ink-muted dark:bg-white/5"><tr><th className="px-4 py-3">Name</th><th>Username</th><th>Role</th><th>Access</th><th>Active</th><th className="pr-4 text-right">Actions</th></tr></thead><tbody className="divide-y dark:divide-white/5">{loading&&<tr><td colSpan={6} className="p-10 text-center">Loading…</td></tr>}{!loading&&users.map(u=><tr key={u.id}><td className="px-4 py-3"><b>{u.name}</b><div className="text-xs text-ink-muted">{u.email}</div></td><td>{u.username}</td><td><select value={u.role} onChange={e=>patch(u.id,{role:e.target.value,useRoleDefaults:true})} className="rounded border px-2 py-1.5 dark:bg-slate-900">{ROLES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></td><td><button onClick={()=>setPermUser(u)} className="rounded-lg border px-3 py-1.5 text-xs font-semibold text-brand-700"><ShieldCheck className="mr-1 inline h-4 w-4"/>{u.usesCustomPermissions?'Custom':'Role Default'}</button></td><td><button onClick={()=>patch(u.id,{isActive:!u.isActive})} className={`rounded-full px-2.5 py-1 text-xs ${u.isActive?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-500'}`}>{u.isActive?'Active':'Inactive'}</button></td><td className="pr-4 text-right"><button onClick={()=>resetPassword(u.id,u.username)} className="p-2" title="Reset password"><KeyRound className="h-4 w-4"/></button><button onClick={()=>remove(u.id,u.username)} className="p-2 text-red-600" title="Deactivate"><X className="h-4 w-4"/></button></td></tr>)}</tbody></table></div></div>
 {adding&&<AddUserModal onClose={()=>setAdding(false)} onDone={()=>{setAdding(false);load()}} onError={setError}/>} {permUser&&<PermissionsModal user={permUser} onClose={()=>setPermUser(null)} onSave={async b=>{if(await patch(permUser.id,b))setPermUser(null)}}/>}</div>}
function PermissionsModal({user,onClose,onSave}:{user:U;onClose:()=>void;onSave:(b:any)=>void}){const[custom,setCustom]=useState(user.usesCustomPermissions);const[perms,setPerms]=useState<string[]>(user.permissions||[]);const toggle=(p:string)=>setPerms(x=>x.includes(p)?x.filter(v=>v!==p):[...x,p]);return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4" onClick={onClose}><div className="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-white p-5 dark:bg-slate-900" onClick={e=>e.stopPropagation()}><div className="flex justify-between"><div><h3 className="font-bold">Access Control — {user.name}</h3><p className="text-xs text-ink-muted">Give only the modules/actions this user needs.</p></div><button onClick={onClose}><X/></button></div><label className="mt-4 flex items-center gap-2 rounded-xl border p-3"><input type="checkbox" checked={custom} onChange={e=>setCustom(e.target.checked)}/><span className="text-sm font-semibold">Use custom permissions</span></label>{custom&&<div className="mt-4 grid gap-4 md:grid-cols-2">{GROUPS.map(([g,ps])=><div key={g} className="rounded-xl border p-3"><h4 className="mb-2 font-semibold">{g}</h4>{ps.map(p=><label key={p} className="flex items-center gap-2 py-1 text-sm"><input type="checkbox" checked={perms.includes(p)} onChange={()=>toggle(p)}/>{LABEL[p]||p}</label>)}</div>)}</div>}<div className="mt-5 flex justify-end gap-2"><button onClick={onClose} className="rounded-xl px-4 py-2">Cancel</button><Button onClick={()=>onSave(custom?{permissions:perms}:{useRoleDefaults:true})}><Save className="h-4 w-4"/>Save Access</Button></div></div></div>}
function AddUserModal({onClose,onDone,onError}:{onClose:()=>void;onDone:()=>void;onError:(m:string)=>void}){const[f,setF]=useState({name:'',username:'',email:'',password:'',role:'VIEWER'}),[busy,setBusy]=useState(false);const set=(k:string,v:string)=>setF(p=>({...p,[k]:v}));async function submit(){if(!f.name||!f.username||!f.email||!f.password)return onError('Fill in all fields.');setBusy(true);const r=await fetch('/api/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(f)});const d=await r.json();setBusy(false);if(!r.ok)return onError(d.error||'Could not create');onDone()}return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" onClick={onClose}><div className="w-full max-w-md rounded-2xl bg-white p-5 dark:bg-slate-900" onClick={e=>e.stopPropagation()}><div className="mb-4 flex justify-between"><b>Add user</b><button onClick={onClose}><X/></button></div><div className="space-y-3">{(['name','username','email','password'] as const).map(k=><label key={k} className="block"><span className="mb-1 block text-xs capitalize">{k}</span><input type={k==='password'?'password':'text'} value={f[k]} onChange={e=>set(k,e.target.value)} className="w-full rounded-lg border px-3 py-2 dark:bg-slate-950"/></label>)}<select value={f.role} onChange={e=>set('role',e.target.value)} className="w-full rounded-lg border px-3 py-2 dark:bg-slate-950">{ROLES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div><div className="mt-5 flex justify-end gap-2"><button onClick={onClose}>Cancel</button><Button onClick={submit} loading={busy}>Create user</Button></div></div></div>}
