"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import {useRouter} from "next/navigation";
import {ChevronDown,ChevronUp,Eraser,History,PackagePlus,Pencil,Plus,Printer,Search,Settings2,ShieldCheck,Trash2,Wrench,X} from "lucide-react";
import {Button} from "@/components/ui/button";
import {WORKSHOP_STATUSES,jobStatusMeta} from "@/lib/workshop";
import {SignaturePad,type SignaturePadHandle} from "@/components/workshop/signature-pad";
import {JobCardPrint,type PrintJob} from "@/components/workshop/jobcard-print";
import {RECEIVING_CHECKLIST,emptyChecklist,type ChecklistMap} from "@/lib/qc-checklists";

type Job=PrintJob&{id:string;createdAt:string;customerId:string|null;vehicleId:string|null;emailStatus:string|null;inTime?:string|null;address?:string|null};
type StockItem={id:string;sku:string;name:string;partNumber:string|null;oemNumber:string|null;currentStock:number;locations:{id:string;quantity:number;reservedQty:number;label:string}[]};
type Company={name?:string;address?:string;phone?:string;email?:string;website?:string;gstin?:string;logoDataUrl?:string};
const input="w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm outline-none focus:border-brand-300 focus:ring-2 focus:ring-brand-200 dark:border-white/10 dark:bg-white/5";
const yesNo=['YES','NO'];
const defaultBrands=['Mercedes-Benz','BMW','Audi','Jaguar','Land Rover','Volvo','Porsche','Lexus','Toyota','Honda','Skoda','Jeep','KIA','Hyundai','MG'];
const defaultServices=['General Service','Oil Change','AC Service','Body Paint','Coolant Leakage','Brake Service','Transmission Oil Change','Electrical Issue','Air Bag Light','Self Problem','Service And Dry Clean','Rubbing Polishing','Diagnosis / Inspection','Accidental Repair'];
function initial(){const n=new Date();return{customerId:'',vehicleId:'',customerName:'',contactNo:'',emailId:'',address:'',vehicleNo:'',carBrand:'',model:'',variant:'',chassisNumber:'',engineNumber:'',odometer:'',jobDate:n.toISOString().slice(0,10),inTime:n.toTimeString().slice(0,5),serviceType:'',complaint:'',additionalRequests:'',fuelType:'',fuelReading:'Half (50%)',chargingPct:'',headRest:'YES',perfume:'NO',speaker:'YES',jackSet:'YES',toolKit:'NO',spareWheel:'YES',floorMats:'YES',rcBook:'NO',insuranceStatus:'NO',insuranceCompany:'',insuranceExpiry:'',remarks:'',customerSignatureRequired:false,advisorSignatureRequired:false,emailRequested:true}}
function jobToForm(j:Job){const d=new Date(j.receivedAt);return{...initial(),customerId:j.customerId||'',vehicleId:j.vehicleId||'',customerName:j.customerName||'',contactNo:j.contactNo||'',emailId:j.emailId||'',vehicleNo:j.vehicleNo||'',carBrand:j.carBrand||'',model:j.model||'',variant:j.variant||'',chassisNumber:j.chassisNumber||'',engineNumber:j.engineNumber||'',odometer:j.odometer??'',jobDate:d.toISOString().slice(0,10),inTime:j.inTime||d.toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'}),serviceType:j.serviceType||'',complaint:j.complaint||'',additionalRequests:j.additionalRequests||'',fuelType:j.fuelType||'',fuelReading:j.fuelReading||'Half (50%)',headRest:j.headRest||'YES',perfume:j.perfume||'NO',speaker:j.speaker||'YES',jackSet:j.jackSet||'YES',toolKit:j.toolKit||'NO',spareWheel:j.spareWheel||'YES',floorMats:j.floorMats||'YES',rcBook:j.rcBook||'NO',insuranceStatus:j.insuranceStatus||'NO',insuranceCompany:j.insuranceCompany||'',insuranceExpiry:j.insuranceExpiry?String(j.insuranceExpiry).slice(0,10):'',remarks:j.remarks||'',customerSignatureRequired:false,advisorSignatureRequired:false,emailRequested:true}}

export function WorkshopClient({jobs,stockItems,canManage,company,documents}:{jobs:Job[];stockItems:StockItem[];canManage:boolean;company:Company;documents:any}){
 const r=useRouter();const[f,setF]=useState<any>(initial());const set=(k:string,v:any)=>setF((p:any)=>({...p,[k]:v}));
 const[receiving,setReceiving]=useState<ChecklistMap>(emptyChecklist(RECEIVING_CHECKLIST));const[inspectionOpen,setInspectionOpen]=useState(true);const[formOpen,setFormOpen]=useState(false),[editingJob,setEditingJob]=useState<Job|null>(null),[busy,setBusy]=useState(false),[err,setErr]=useState<string|null>(null),[search,setSearch]=useState(''),[results,setResults]=useState<any[]>([]),[selectedHistory,setSelectedHistory]=useState<any[]>([]),[showHistory,setShowHistory]=useState(false);
 const custRef=useRef<SignaturePadHandle>(null),advRef=useRef<SignaturePadHandle>(null);const[printJob,setPrintJob]=useState<PrintJob|null>(null),[partJob,setPartJob]=useState<Job|null>(null),[partSearch,setPartSearch]=useState(''),[selectedItem,setSelectedItem]=useState(''),[locationId,setLocationId]=useState(''),[partQty,setPartQty]=useState('1'),[partNote,setPartNote]=useState(''),[partBusy,setPartBusy]=useState(false),[statusRemark,setStatusRemark]=useState<Record<string,string>>({});
 const[jobQuery,setJobQuery]=useState(''),[statusFilter,setStatusFilter]=useState('ALL'),[serviceFilter,setServiceFilter]=useState('ALL'),[activeTab,setActiveTab]=useState<'OPEN'|'DELIVERED'>('OPEN');
 const[brands,setBrands]=useState<string[]>(defaultBrands),[services,setServices]=useState<string[]>(defaultServices),[manageKind,setManageKind]=useState<'brand'|'service'|null>(null);
 useEffect(()=>{fetch('/api/workshop-options').then(x=>x.json()).then(d=>{if(d.brands)setBrands(d.brands);if(d.services)setServices(d.services)}).catch(()=>{})},[]);
 useEffect(()=>{if(search.trim().length<2){setResults([]);return}const t=setTimeout(async()=>{try{const d=await(await fetch('/api/customers/search?q='+encodeURIComponent(search))).json();setResults(d.results||[])}catch{}},300);return()=>clearTimeout(t)},[search]);
 function choose(c:any,v?:any){const x=v||c.vehicles?.[0];set('customerId',c.id);set('customerName',c.name||'');set('contactNo',c.phone||'');set('emailId',c.email||'');set('address',c.address||'');if(x){set('vehicleId',x.id);set('vehicleNo',x.registration||'');set('carBrand',x.brand||'');set('model',x.modelName||'');set('variant',x.variant||'');set('chassisNumber',x.chassisNumber||'');set('engineNumber',x.engineNumber||'');set('odometer',x.lastOdometer||'');set('fuelType',x.fuelType||'')}setSelectedHistory(c.workshopJobs||[]);setSearch('');setResults([])}
 function updCheck(key:string,k:'status'|'comment',v:string){setReceiving(p=>({...p,[key]:{...(p[key]||{status:'NOT_CHECKED'}),[k]:v as any}}))}
 function resetForm(){setF(initial());setReceiving(emptyChecklist(RECEIVING_CHECKLIST));setEditingJob(null);setErr(null)}
 function startNew(){resetForm();setFormOpen(true)}
 function startEdit(j:Job){setEditingJob(j);setF(jobToForm(j));setReceiving((j.receivingChecklist as ChecklistMap)||emptyChecklist(RECEIVING_CHECKLIST));setFormOpen(true);window.scrollTo({top:0,behavior:'smooth'})}
 async function saveJob(){setErr(null);for(const[k,l]of[['customerName','Customer Name'],['contactNo','Mobile Number'],['vehicleNo','Car Registration'],['carBrand','Car Brand'],['serviceType','Service Type']] as const)if(!String(f[k]||'').trim())return setErr(`${l} is required.`);setBusy(true);try{const payload={...f,mode:editingJob?'EDIT':undefined,receivingChecklist:receiving,fuelReading:f.fuelType==='Electric'?`Charging: ${f.chargingPct||'--'}%`:f.fuelReading,custSignature:f.customerSignatureRequired?custRef.current?.getDataUrl()||null:null,advisorSignature:f.advisorSignatureRequired?advRef.current?.getDataUrl()||null:null};const url=editingJob?`/api/workshop-jobs/${editingJob.id}`:'/api/workshop-jobs';const res=await fetch(url,{method:editingJob?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await res.json();if(!res.ok)throw new Error(d.error||'Could not save job card');resetForm();setFormOpen(false);r.refresh()}catch(e:any){setErr(e.message)}finally{setBusy(false)}}
 async function updateJob(j:Job,status:string){const res=await fetch(`/api/workshop-jobs/${j.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status,remark:statusRemark[j.id]||''})});if(res.ok){setStatusRemark(p=>({...p,[j.id]:''}));r.refresh()}}
 const filtered=useMemo(()=>{const q=jobQuery.trim().toLowerCase();return jobs.filter(j=>{const section=activeTab==='DELIVERED'?j.status==='DELIVERED':j.status!=='DELIVERED';if(!section)return false;if(statusFilter!=='ALL'&&j.status!==statusFilter)return false;if(serviceFilter!=='ALL'&&j.serviceType!==serviceFilter)return false;return !q||`${j.jobNumber} ${j.customerName||''} ${j.contactNo||''} ${j.vehicleNo||''} ${j.carBrand||''} ${j.model||''} ${j.serviceType||''} ${j.status}`.toLowerCase().includes(q)})},[jobs,jobQuery,statusFilter,serviceFilter,activeTab]);
 const openCount=jobs.filter(j=>j.status!=='DELIVERED').length,deliveredCount=jobs.filter(j=>j.status==='DELIVERED').length;
 const item=stockItems.find(x=>x.id===selectedItem),filteredItems=stockItems.filter(x=>!partSearch||`${x.sku} ${x.name} ${x.partNumber||''} ${x.oemNumber||''}`.toLowerCase().includes(partSearch.toLowerCase())).slice(0,50);
 async function issue(){if(!partJob||!selectedItem||!locationId||Number(partQty)<=0)return;setPartBusy(true);const res=await fetch(`/api/workshop-jobs/${partJob.id}/parts`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({itemId:selectedItem,locationStockId:locationId,quantity:Number(partQty),note:partNote})});const d=await res.json();setPartBusy(false);if(!res.ok)return alert(d.error||'Issue failed');setPartJob(null);r.refresh()}
 async function returnPart(j:Job,p:any){const max=p.quantity-p.returnedQty,entered=window.prompt(`Return quantity (max ${max})`,String(max));if(!entered)return;const res=await fetch(`/api/workshop-jobs/${j.id}/parts`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({partId:p.id,returnQty:Number(entered)})});if(res.ok)r.refresh()}
 return <div className="space-y-5">
  <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="font-display text-2xl font-bold">Job Cards</h1><p className="text-sm text-ink-muted">Vehicle receiving, service tracking, parts issue/return and complete job history.</p></div>{canManage&&<Button onClick={()=>formOpen?(setFormOpen(false),resetForm()):startNew()}><Wrench className="h-4 w-4"/>{formOpen?'Close Form':'New Job Card'}</Button>}</div>
  {formOpen&&<div className="space-y-4 rounded-2xl border border-brand-100 bg-brand-50/20 p-3"><div className="flex items-center justify-between"><div><b>{editingJob?`Edit ${editingJob.jobNumber}`:'Create New Job Card'}</b>{editingJob&&<div className="text-xs text-ink-muted">Job number remains unchanged. All edits are logged.</div>}</div>{editingJob&&<button onClick={()=>{resetForm();setFormOpen(false)}} className="rounded-lg p-2 hover:bg-white"><X className="h-4 w-4"/></button>}</div>
   {!editingJob&&<Card title="Customer Lookup" icon={<Search className="h-4 w-4"/>}><div className="relative sm:col-span-2 lg:col-span-3"><input className={input} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search mobile, customer, registration or chassis..."/>{results.length>0&&<div className="absolute z-20 mt-1 max-h-64 w-full overflow-auto rounded-xl border bg-white shadow-xl dark:bg-slate-900">{results.map(c=><div key={c.id} className="border-b p-2"><button className="w-full text-left text-sm font-bold" onClick={()=>choose(c)}>{c.name} · {c.phone}</button>{c.vehicles?.map((v:any)=><button key={v.id} onClick={()=>choose(c,v)} className="ml-3 block text-xs text-brand-600">{v.registration} · {v.brand} {v.modelName} · {v.chassisNumber||''}</button>)}</div>)}</div>}</div>{selectedHistory.length>0&&<div className="sm:col-span-2 lg:col-span-3"><button onClick={()=>setShowHistory(!showHistory)} className="flex items-center gap-2 text-xs font-semibold text-brand-600"><History className="h-4 w-4"/>Previous Service History {showHistory?<ChevronUp/>:<ChevronDown/>}</button>{showHistory&&<div className="mt-2 rounded border p-2 text-xs">{selectedHistory.map((h:any)=><div key={h.id}>{h.jobNumber} · {h.serviceType} · {h.status}</div>)}</div>}</div>}</Card>}
   <Card title="Customer & Vehicle"><Text l="Customer Name *" v={f.customerName} s={v=>set('customerName',v)}/><Text l="Mobile *" v={f.contactNo} s={v=>set('contactNo',v)}/><Text l="Email" v={f.emailId} s={v=>set('emailId',v)}/><Text l="Address" v={f.address} s={v=>set('address',v)}/><Text l="Registration *" v={f.vehicleNo} s={v=>set('vehicleNo',v.toUpperCase())}/><ManageSelect l="Brand *" v={f.carBrand} s={v=>set('carBrand',v)} o={brands} canManage={canManage} manage={()=>setManageKind('brand')}/><Text l="Model" v={f.model} s={v=>set('model',v)}/><Text l="Variant" v={f.variant} s={v=>set('variant',v)}/><Text l="Chassis Number" v={f.chassisNumber} s={v=>set('chassisNumber',v)}/><Text l="Engine Number" v={f.engineNumber} s={v=>set('engineNumber',v)}/><Text l="Odometer (KM)" v={f.odometer} s={v=>set('odometer',v)} type="number"/></Card>
   <Card title="Job / Service"><Text l="Date" v={f.jobDate} s={v=>set('jobDate',v)} type="date"/><Text l="In Time" v={f.inTime} s={v=>set('inTime',v)} type="time"/><ManageSelect l="Service Type *" v={f.serviceType} s={v=>set('serviceType',v)} o={services} canManage={canManage} manage={()=>setManageKind('service')}/><Area l="Complaint / Work Required" v={f.complaint} s={v=>set('complaint',v)}/><Area l="Additional Request" v={f.additionalRequests} s={v=>set('additionalRequests',v)}/></Card>
   <div className="rounded-2xl border bg-white shadow-card dark:border-white/10 dark:bg-[rgb(var(--surface))]"><button onClick={()=>setInspectionOpen(!inspectionOpen)} className="flex w-full items-center justify-between p-4 text-left"><div className="flex items-center gap-2 font-semibold text-brand-700"><ShieldCheck className="h-5 w-5"/>Vehicle Receiving / Working Check</div>{inspectionOpen?<ChevronUp/>:<ChevronDown/>}</button>{inspectionOpen&&<div className="space-y-3 border-t p-3">{RECEIVING_CHECKLIST.map(sec=><div key={sec.title} className="overflow-hidden rounded-xl border"><div className="bg-slate-50 px-3 py-2 text-sm font-bold dark:bg-white/5">{sec.title}</div>{sec.items.map(i=><div key={i.key} className="grid gap-2 border-t p-2 sm:grid-cols-[1fr_130px_1fr]"><span className="text-sm">{i.label}</span><select className={input} value={receiving[i.key]?.status||'NOT_CHECKED'} onChange={e=>updCheck(i.key,'status',e.target.value)}><option value="NOT_CHECKED">Not checked</option><option value="OK">✓ OK / Working</option><option value="NOT_WORKING">Not Working</option><option value="DAMAGE">Issue / Damage</option><option value="NA">N/A</option></select><input className={input} placeholder="Condition / defect comment" value={receiving[i.key]?.comment||''} onChange={e=>updCheck(i.key,'comment',e.target.value)}/></div>)}</div>)}</div>}</div>
   <Card title="Fuel / Accessories / Documents"><Select l="Fuel Type" v={f.fuelType} s={v=>set('fuelType',v)} o={['Petrol','Diesel','CNG','Hybrid','Electric']}/>{f.fuelType==='Electric'?<Text l="Charging %" v={f.chargingPct} s={v=>set('chargingPct',v)} type="number"/>:<Select l="Fuel Level" v={f.fuelReading} s={v=>set('fuelReading',v)} o={['Empty','1/4 (25%)','Half (50%)','3/4 (75%)','Full']}/>}<Select l="Head Rest" v={f.headRest} s={v=>set('headRest',v)} o={yesNo}/><Select l="Perfume" v={f.perfume} s={v=>set('perfume',v)} o={yesNo}/><Select l="Speaker" v={f.speaker} s={v=>set('speaker',v)} o={yesNo}/><Select l="Jack Set" v={f.jackSet} s={v=>set('jackSet',v)} o={yesNo}/><Select l="Tool Kit" v={f.toolKit} s={v=>set('toolKit',v)} o={yesNo}/><Select l="Spare Wheel" v={f.spareWheel} s={v=>set('spareWheel',v)} o={yesNo}/><Select l="Floor Mats" v={f.floorMats} s={v=>set('floorMats',v)} o={yesNo}/><Select l="RC Book" v={f.rcBook} s={v=>set('rcBook',v)} o={yesNo}/><Select l="Insurance" v={f.insuranceStatus} s={v=>set('insuranceStatus',v)} o={yesNo}/>{f.insuranceStatus==='YES'&&<><Text l="Insurance Company" v={f.insuranceCompany} s={v=>set('insuranceCompany',v)}/><Text l="Insurance Expiry" v={f.insuranceExpiry} s={v=>set('insuranceExpiry',v)} type="date"/></>}</Card>
   {!editingJob&&<Card title="Signatures / Remarks"><Sig title="Customer Signature" enabled={f.customerSignatureRequired} toggle={v=>set('customerSignatureRequired',v)} pad={custRef}/><Sig title="Advisor / Executive Signature" enabled={f.advisorSignatureRequired} toggle={v=>set('advisorSignatureRequired',v)} pad={advRef}/><Area l="Remarks" v={f.remarks} s={v=>set('remarks',v)}/></Card>}
   {err&&<p className="rounded bg-red-50 p-2 text-sm text-red-600">{err}</p>}<div className="flex justify-end"><Button onClick={saveJob} loading={busy}>{editingJob?'Save Changes':'Create Job Card'}</Button></div>
  </div>}
  <div className="rounded-2xl border bg-white p-3 shadow-card dark:border-white/10 dark:bg-[rgb(var(--surface))]"><div className="flex flex-wrap gap-2 border-b pb-3"><button onClick={()=>setActiveTab('OPEN')} className={`rounded-xl px-4 py-2 text-sm font-semibold ${activeTab==='OPEN'?'bg-brand-600 text-white':'bg-slate-100 text-slate-700'}`}>Open / Running Jobs ({openCount})</button><button onClick={()=>setActiveTab('DELIVERED')} className={`rounded-xl px-4 py-2 text-sm font-semibold ${activeTab==='DELIVERED'?'bg-emerald-600 text-white':'bg-slate-100 text-slate-700'}`}>Delivered History ({deliveredCount})</button></div><div className="grid gap-2 pt-3 md:grid-cols-[1fr_180px_220px]"><div className="flex items-center gap-2 rounded-xl border px-3"><Search className="h-4 w-4"/><input className="w-full bg-transparent py-2.5 text-sm outline-none" value={jobQuery} onChange={e=>setJobQuery(e.target.value)} placeholder="Search Job No / customer / mobile / vehicle..."/></div><select className={input} value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="ALL">All Status</option>{WORKSHOP_STATUSES.filter(s=>activeTab==='DELIVERED'?s==='DELIVERED':s!=='DELIVERED').map(s=><option key={s} value={s}>{jobStatusMeta(s)[0]}</option>)}</select><select className={input} value={serviceFilter} onChange={e=>setServiceFilter(e.target.value)}><option value="ALL">All Service Types</option>{services.map(s=><option key={s} value={s}>{s}</option>)}</select></div></div>
  <div className="overflow-x-auto rounded-2xl border bg-white dark:border-white/10 dark:bg-[rgb(var(--surface))]"><table className="min-w-[1080px] w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-ink-muted dark:bg-white/5"><tr><th className="p-3">Job Card</th><th>Customer / Vehicle</th><th>Service</th><th>Parts</th><th>Status / Remark</th><th className="text-right pr-4">Actions</th></tr></thead><tbody className="divide-y dark:divide-white/5">{filtered.length===0&&<tr><td colSpan={6} className="p-10 text-center text-ink-muted">No job cards found in this section.</td></tr>}{filtered.map(j=>{const[label,cls]=jobStatusMeta(j.status);return <tr key={j.id} className="align-top"><td className="p-3"><b>{j.jobNumber}</b><div className="text-xs text-ink-muted">{new Date(j.receivedAt).toLocaleString('en-IN')}</div></td><td><b>{j.customerName}</b><div>{j.contactNo}</div><div className="text-xs text-ink-muted">{j.vehicleNo} · {j.carBrand} {j.model}</div></td><td>{j.serviceType||'—'}<div className="max-w-xs truncate text-xs text-ink-muted">{j.complaint||''}</div></td><td>Lines: {j.parts?.length||0}<div className="text-xs">Net Qty: {(j.parts||[]).reduce((a,p)=>a+(p.quantity-p.returnedQty),0)}</div></td><td>{canManage?<><select className={`${input} max-w-[190px]`} value={j.status} onChange={e=>updateJob(j,e.target.value)}>{WORKSHOP_STATUSES.map(s=><option key={s}>{s}</option>)}</select><div className="mt-2 flex gap-1"><input className="w-36 rounded border px-2 py-1 text-xs" value={statusRemark[j.id]||''} onChange={e=>setStatusRemark(p=>({...p,[j.id]:e.target.value}))} placeholder="remark"/><button onClick={()=>updateJob(j,j.status)} className="rounded border px-2 text-xs">Add</button></div></>:<span className={cls}>{label}</span>}</td><td className="p-3"><div className="flex justify-end gap-2">{canManage&&<button title="Edit Job Card" onClick={()=>startEdit(j)} className="rounded border p-2 text-amber-600"><Pencil className="h-4 w-4"/></button>}<button title="Print Job Card" onClick={()=>setPrintJob(j)} className="rounded border p-2 text-brand-600"><Printer className="h-4 w-4"/></button>{canManage&&j.status!=='DELIVERED'&&<button title="Issue Part" onClick={()=>setPartJob(j)} className="rounded border p-2 text-emerald-600"><PackagePlus className="h-4 w-4"/></button>}</div>{j.parts.filter(p=>p.quantity>p.returnedQty).slice(0,3).map(p=><button key={p.id} onClick={()=>returnPart(j,p)} className="mt-1 block w-full text-right text-[10px] text-amber-700">Return {p.item.partNumber||p.item.sku} ({p.quantity-p.returnedQty})</button>)}</td></tr>})}</tbody></table></div>
  {manageKind&&<OptionsModal kind={manageKind} values={manageKind==='brand'?brands:services} onClose={()=>setManageKind(null)} onChange={v=>manageKind==='brand'?setBrands(v):setServices(v)}/>} 
  {partJob&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div className="w-full max-w-2xl rounded-2xl bg-white p-5 dark:bg-slate-900"><div className="mb-4 flex justify-between"><b>Issue Part to {partJob.jobNumber}</b><button onClick={()=>setPartJob(null)}><X/></button></div><input className={input} value={partSearch} onChange={e=>setPartSearch(e.target.value)} placeholder="Search part..."/><div className="mt-3 grid gap-3 sm:grid-cols-2"><SelectNode l="Part" v={selectedItem} s={v=>{setSelectedItem(v);setLocationId('')}}><option value="">— Select —</option>{filteredItems.map(x=><option key={x.id} value={x.id}>{x.partNumber||x.sku} · {x.name} · Stock {x.currentStock}</option>)}</SelectNode><SelectNode l="Exact Location" v={locationId} s={setLocationId}><option value="">— Select —</option>{item?.locations.filter(l=>l.quantity-l.reservedQty>0).map(l=><option key={l.id} value={l.id}>{l.label} · Avl {l.quantity-l.reservedQty}</option>)}</SelectNode><Text l="Qty" v={partQty} s={setPartQty} type="number"/><Text l="Note" v={partNote} s={setPartNote}/></div><div className="mt-4 flex justify-end"><Button onClick={issue} loading={partBusy}>Issue & Deduct Stock</Button></div></div></div>}
  {printJob&&<JobCardPrint job={printJob} company={company} documents={documents} onClose={()=>setPrintJob(null)}/>} 
 </div>
}
function OptionsModal({kind,values,onClose,onChange}:{kind:'brand'|'service';values:string[];onClose:()=>void;onChange:(v:string[])=>void}){const[value,setValue]=useState(''),[busy,setBusy]=useState(false),[err,setErr]=useState('');async function add(){if(!value.trim())return;setBusy(true);const res=await fetch('/api/workshop-options',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind,value})});const d=await res.json();setBusy(false);if(!res.ok)return setErr(d.error||'Could not add');onChange(d.values);setValue('')}async function del(v:string){if(!confirm(`Remove ${v}? Existing job cards will not be changed.`))return;const res=await fetch('/api/workshop-options',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind,value:v})});const d=await res.json();if(res.ok)onChange(d.values)}return <div className="fixed inset-0 z-[80] flex items-center justify-center bg-black/50 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-5 shadow-xl dark:bg-slate-900"><div className="mb-4 flex justify-between"><div><b>Manage {kind==='brand'?'Brands':'Service Types'}</b><p className="text-xs text-ink-muted">Add options here; dropdown updates immediately.</p></div><button onClick={onClose}><X/></button></div><div className="flex gap-2"><input className={input} value={value} onChange={e=>setValue(e.target.value)} placeholder={`New ${kind==='brand'?'brand':'service type'}`} onKeyDown={e=>e.key==='Enter'&&add()}/><Button onClick={add} loading={busy}><Plus className="h-4 w-4"/>Add</Button></div>{err&&<p className="mt-2 text-xs text-red-600">{err}</p>}<div className="mt-4 max-h-72 overflow-auto rounded-xl border">{values.map(v=><div key={v} className="flex items-center justify-between border-b px-3 py-2 text-sm last:border-0"><span>{v}</span><button onClick={()=>del(v)} className="rounded p-1.5 text-red-500 hover:bg-red-50"><Trash2 className="h-4 w-4"/></button></div>)}</div></div></div>}
function Card({title,icon,children}:{title:string;icon?:React.ReactNode;children:React.ReactNode}){return <div className="rounded-2xl border bg-white p-4 shadow-card dark:border-white/10 dark:bg-[rgb(var(--surface))]"><div className="mb-3 flex items-center gap-2 text-sm font-semibold text-brand-700">{icon}{title}</div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{children}</div></div>}
function Text({l,v,s,type='text'}:{l:string;v:any;s:(v:string)=>void;type?:string}){return <label><span className="mb-1 block text-xs text-ink-muted">{l}</span><input type={type} className={input} value={v??''} onChange={e=>s(e.target.value)}/></label>}
function Area({l,v,s}:{l:string;v:any;s:(v:string)=>void}){return <label className="sm:col-span-2"><span className="mb-1 block text-xs text-ink-muted">{l}</span><textarea className={input} rows={3} value={v??''} onChange={e=>s(e.target.value)}/></label>}
function Select({l,v,s,o}:{l:string;v:string;s:(v:string)=>void;o:string[]}){return <label><span className="mb-1 block text-xs text-ink-muted">{l}</span><select className={input} value={v} onChange={e=>s(e.target.value)}><option value="">— Select —</option>{o.map(x=><option key={x}>{x}</option>)}</select></label>}
function ManageSelect({l,v,s,o,canManage,manage}:{l:string;v:string;s:(v:string)=>void;o:string[];canManage:boolean;manage:()=>void}){return <label><span className="mb-1 flex items-center justify-between text-xs text-ink-muted"><span>{l}</span>{canManage&&<button type="button" onClick={manage} className="flex items-center gap-1 font-semibold text-brand-600"><Settings2 className="h-3 w-3"/>Add / Manage</button>}</span><select className={input} value={v} onChange={e=>s(e.target.value)}><option value="">— Select —</option>{o.map(x=><option key={x}>{x}</option>)}</select></label>}
function SelectNode({l,v,s,children}:{l:string;v:string;s:(v:string)=>void;children:React.ReactNode}){return <label><span className="mb-1 block text-xs text-ink-muted">{l}</span><select className={input} value={v} onChange={e=>s(e.target.value)}>{children}</select></label>}
function Sig({title,enabled,toggle,pad}:{title:string;enabled:boolean;toggle:(v:boolean)=>void;pad:React.Ref<SignaturePadHandle>}){return <div className="rounded-xl border p-3"><div className="mb-2 flex justify-between"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={enabled} onChange={e=>toggle(e.target.checked)}/>{title}</label>{enabled&&<Eraser className="h-4 w-4" onClick={()=>('current'in (pad as any))&&(pad as any).current?.clear()}/>}</div>{enabled?<SignaturePad ref={pad}/>:<div className="py-6 text-center text-xs text-ink-muted">Not required</div>}</div>}
