"use client";
import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { Plus, Search, Users, Car } from "lucide-react";
import { Button } from "@/components/ui/button";
const input="w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm outline-none focus:border-brand-300 focus:ring-2 focus:ring-brand-200 dark:border-white/10 dark:bg-white/5";
export function CustomersClient({initial,canManage}:{initial:any[];canManage:boolean}){
 const r=useRouter(); const [q,setQ]=useState(""); const [open,setOpen]=useState(false); const [busy,setBusy]=useState(false); const [err,setErr]=useState<string|null>(null);
 const [f,setF]=useState({name:"",phone:"",altPhone:"",email:"",gstin:"",address:"",city:"",state:"",pincode:"",notes:""});
 const rows=useMemo(()=>initial.filter(c=>JSON.stringify(c).toLowerCase().includes(q.toLowerCase())),[initial,q]);
 async function save(){setErr(null);if(!f.name.trim())return setErr("Customer name required.");setBusy(true);try{const res=await fetch('/api/customers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(f)});const d=await res.json();if(!res.ok)throw new Error(d.error||'Could not save');setOpen(false);setF({name:"",phone:"",altPhone:"",email:"",gstin:"",address:"",city:"",state:"",pincode:"",notes:""});r.refresh()}catch(e:any){setErr(e.message)}finally{setBusy(false)}}
 return <div className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="font-display text-2xl font-bold text-ink dark:text-slate-100">Customer Master</h1><p className="text-sm text-ink-muted">Customer profile, vehicles and workshop relationship.</p></div>{canManage&&<Button onClick={()=>setOpen(v=>!v)}><Plus className="h-4 w-4"/>New Customer</Button>}</div>
 {open&&<div className="rounded-2xl border bg-white p-5 shadow-card dark:border-white/10 dark:bg-[rgb(var(--surface))]"><h3 className="mb-4 font-semibold">Add customer</h3>{err&&<p className="mb-3 rounded bg-red-50 p-2 text-sm text-red-600">{err}</p>}<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{Object.entries({name:'Customer Name *',phone:'Mobile',altPhone:'Alternate Mobile',email:'Email',gstin:'GSTIN',address:'Address',city:'City',state:'State',pincode:'Pincode',notes:'Notes'}).map(([k,l])=><label key={k}><span className="mb-1 block text-xs text-ink-muted">{l}</span><input className={input} value={(f as any)[k]} onChange={e=>setF(p=>({...p,[k]:e.target.value}))}/></label>)}</div><div className="mt-4 flex justify-end"><Button onClick={save} loading={busy}>Save Customer</Button></div></div>}
 <div className="flex max-w-xl items-center gap-2 rounded-xl border bg-white px-3 dark:border-white/10 dark:bg-white/5"><Search className="h-4 w-4 text-ink-muted"/><input className="w-full bg-transparent py-2.5 text-sm outline-none" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search name, mobile, email, registration, VIN..."/></div>
 <div className="overflow-hidden rounded-2xl border bg-white shadow-card dark:border-white/10 dark:bg-[rgb(var(--surface))]"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-ink-muted dark:bg-white/5"><tr><th className="px-4 py-3">Customer</th><th>Contact</th><th>City</th><th>Vehicles</th><th>Created</th></tr></thead><tbody className="divide-y dark:divide-white/5">{rows.map(c=><tr key={c.id}><td className="px-4 py-3"><div className="font-semibold">{c.name}</div><div className="text-xs text-ink-muted">{c.code}</div></td><td>{c.phone||'—'}<div className="text-xs text-ink-muted">{c.email||''}</div></td><td>{[c.city,c.state].filter(Boolean).join(', ')||'—'}</td><td><div className="flex items-center gap-1"><Car className="h-3.5 w-3.5"/>{c.vehicles.length}</div>{c.vehicles.slice(0,2).map((v:any)=><div key={v.id} className="text-xs text-ink-muted">{v.registration||v.chassisNumber} · {v.brand||''} {v.modelName||''}</div>)}</td><td className="text-xs text-ink-muted">{new Date(c.createdAt).toLocaleDateString('en-IN')}</td></tr>)}{!rows.length&&<tr><td colSpan={5} className="py-16 text-center text-ink-muted"><Users className="mx-auto mb-2 h-8 w-8 opacity-40"/>No customers</td></tr>}</tbody></table></div></div></div>
}
